### ISSUE TITLE
Armv7l的AC68U不能安装啊

### ISSUE THREAD

**Issue by sleepingsentry** [learnhard-cn/clash#1]
下了几个版本的包都是一样的结果。用离线安装提示：你上传的离线安装包不是【koolshare merlin armv7l 384/386】平台的离线包；用ssh的方式安装，运行tar zcvf clash.tar.gz clash了之后报错（显示的是乱码）。我看了下命令行里面只有armv5和armv8，是不是因为这里缺少了7导致的？

**Comment by Awkee** [comment]
> 下了几个版本的包都是一样的结果。用离线安装提示：你上传的离线安装包不是【koolshare merlin armv7l 384/386】平台的离线包；用ssh的方式安装，运行tar zcvf clash.tar.gz clash了之后报错（显示的是乱码）。我看了下命令行里面只有armv5和armv8，是不是因为这里缺少了7导致的？

armv7l使用的是armv5可执行程序即可, 可能AC68U需要适配后你才能用，你可以在 /koolshare/scripts/ks_tar_install.sh 里面找到报错的检测规则。如果你了解脚本规则可以尝试自己修改，成功后提交给我合并一下，或者把这个脚本上传上来我看下。

**Comment by sleepingsentry** [comment]
> > 下了几个版本的包都是一样的结果。用离线安装提示：你上传的离线安装包不是【koolshare merlin armv7l 384/386】平台的离线包；用ssh的方式安装，运行tar zcvf clash.tar.gz clash了之后报错（显示的是乱码）。我看了下命令行里面只有armv5和armv8，是不是因为这里缺少了7导致的？
> 
> armv7l使用的是armv5可执行程序即可, 可能AC68U需要使用v2版本的安装包，v1.9版本是380版本固件用的。
> 
> 你是不是下载错了版本。 试试 release 分支的包: https://github.com/learnhard-cn/clash/tree/release

抱歉之前说的有一点小错，主要是命令行中，用ssh的方式安装，运行第三步的 sh clash/install.sh 之后报错，显示为：
/tmp$ sh clash/install.sh
2021骞?1鏈?4鏃?3:36:10:clash: 姊呮灄鍥轰欢鐗堟湰锛?386
2021骞?1鏈?4鏃?3:36:10:clash: 鎮ㄥ綋鍓嶅浐浠剁増鏈? 386 , Linux鍐呮牳鐗堟湰:2.6.36.4brcmarm

离线安装的提示为

【2021年11月04日 13:33:46】: 检测到你上传的离线安装包：clash.v2.0.7.tar.gz，安装包大小: 9.7M
【2021年11月04日 13:33:46】: 安装包md5sum校验值：48241b6ffbe2207f6916c71149a47b19
【2021年11月04日 13:33:46】: 尝试解压离线安装包离线安装包...
【2021年11月04日 13:33:47】: 安装包解压成功！继续！
【2021年11月04日 13:33:47】: 你上传的离线安装包不是【koolshare merlin armv7l 384/386】平台的离线包！！！
【2021年11月04日 13:33:47】: 请上传正确的离线安装包！！！
【2021年11月04日 13:33:47】: 删除相关文件并退出...
【2021年11月04日 13:33:47】: 删除文件夹-2：/tmp/clash
【2021年11月04日 13:33:47】: 删除文件：/tmp/clash.v2.0.7.tar.gz

另外我明确一下使用的环境：AC68U，固件koolshare的386.3_2。我下的版本是 https://github.com/learnhard-cn/clash/releases/tag/v2.0.6 最新的，然后出问题后之前的几个2.0.x的版本也都试了。刚才你给的网址里的2.0.7也试了，都是一样的问题。

**Comment by Awkee** [comment]
a

> > > 下了几个版本的包都是一样的结果。用离线安装提示：你上传的离线安装包不是【koolshare merlin armv7l 384/386】平台的离线包；用ssh的方式安装，运行tar zcvf clash.tar.gz clash了之后报错（显示的是乱码）。我看了下命令行里面只有armv5和armv8，是不是因为这里缺少了7导致的？
> > 
> > 
> > armv7l使用的是armv5可执行程序即可, 可能AC68U需要使用v2版本的安装包，v1.9版本是380版本固件用的。
> > 你是不是下载错了版本。 试试 release 分支的包: https://github.com/learnhard-cn/clash/tree/release
> 
> 抱歉之前说的有一点小错，拷贝错误。更正为：命令行中，用ssh的方式安装，运行第三步的 **sh clash/install.sh** 之后报错，显示为： /tmp$ sh clash/install.sh 2021骞?1鏈?4鏃?3:36:10:clash: 姊呮灄鍥轰欢鐗堟湰锛?386 2021骞?1鏈?4鏃?3:36:10:clash: 鎮ㄥ綋鍓嶅浐浠剁増鏈? 386 , Linux鍐呮牳鐗堟湰:2.6.36.4brcmarm
> 
> 离线安装的提示为
> 
> 【2021年11月04日 13:33:46】: 检测到你上传的离线安装包：clash.v2.0.7.tar.gz，安装包大小: 9.7M 【2021年11月04日 13:33:46】: 安装包md5sum校验值：48241b6ffbe2207f6916c71149a47b19 【2021年11月04日 13:33:46】: 尝试解压离线安装包离线安装包... 【2021年11月04日 13:33:47】: 安装包解压成功！继续！ 【2021年11月04日 13:33:47】: 你上传的离线安装包不是【koolshare merlin armv7l 384/386】平台的离线包！！！ 【2021年11月04日 13:33:47】: 请上传正确的离线安装包！！！ 【2021年11月04日 13:33:47】: 删除相关文件并退出... 【2021年11月04日 13:33:47】: 删除文件夹-2：/tmp/clash 【2021年11月04日 13:33:47】: 删除文件：/tmp/clash.v2.0.7.tar.gz
> 
> 另外我明确一下使用的环境：AC68U，固件koolshare的386.3_2。我下的版本是 https://github.com/learnhard-cn/clash/releases/tag/v2.0.6 最新的，然后出问题后之前的几个2.0.x的版本也都试了。刚才你给的网址里的2.0.7也试了，都是一样的问题。

.valid 验证规则问题， 试试 v2.0.8 ，更新了一下 .valid 文件。

**Comment by sleepingsentry** [comment]
试了一下2.0.8，还是不行，报错提示是一摸一样的

**Comment by Awkee** [comment]
> 试了一下2.0.8，还是不行，用ssh安装的话，报错提示是一摸一样的； 不过，离线安装的提示有一点不同了，现在是： 【2021年11月04日 14:05:34】: ========================== step 1 =============================== 【2021年11月04日 14:05:34】: 开启插件离线安装！ 【2021年11月04日 14:05:35】: 检测到你上传的离线安装包：clash.v2.0.8.tar.gz，安装包大小: 9.7M 【2021年11月04日 14:05:35】: 安装包md5sum校验值：0694bbabf4dce1928a274b7263988ccb 【2021年11月04日 14:05:35】: 尝试解压离线安装包离线安装包... 【2021年11月04日 14:05:36】: 安装包解压成功！继续！ 【2021年11月04日 14:05:37】: 当前jffs分区剩余：60456KB, 空间满足，继续安装！ 【2021年11月04日 14:05:37】: 准备安装插件：clash 【2021年11月04日 14:05:37】: 当前机型：RT-AC68U 【2021年11月04日 14:05:37】: 当前固件：koolshare梅林改版固件 【2021年11月04日 14:05:37】: 运行安装脚本... 【2021年11月04日 14:05:37】: ========================== step 2 =============================== 2021年11月04日14:05:37:clash: 梅林固件版本： 386 2021年11月04日14:05:37:clash: 您当前固件版本: 386 , Linux内核版本:2.6.36.4brcmarm 【2021年11月04日 14:05:37】: ========================== step 3 =============================== 【2021年11月04日 14:05:37】: ks_tar_install.sh: 因为插件clash安装失败！退出离线安装！ 【2021年11月04日 14:05:37】: 删除文件夹-2：/tmp/clash 【2021年11月04日 14:05:37】: 删除文件：/tmp/clash.v2.0.8.tar.gz 【2021年11月04日 14:05:38】: ============================ end

感谢你的反馈！
这是内核版本验证不符合条件， 我去掉这个内核版本限制条件，更新了v2.0.9版本 , https://github.com/learnhard-cn/clash/tree/release 
请再尝试一次。
