### ISSUE TITLE
2.09在老路由ac68u下clash面板打不开

### ISSUE THREAD

**Issue by qiaosou** [learnhard-cn/clash#2]
命令行查了下，发现没有9090监听，您检查下

**Comment by qiaosou** [comment]
386.3_2 固件是这个

**Comment by Awkee** [comment]
> 386.3_2 固件是这个

**感谢反馈！**

我本地没这个路由器，只能分析看看问题所在了，你描述清楚你当前的状况对我的分析更有帮助：

1. 插件是否可用？点击 `状态检查`显示内容，之后也会把这个9090端口检查也添加进去。
2. 端口检查命令： netstat -anp|grep 9090
3. 检查当前clash服务的端口： netstat -anp|grep clash|grep LISTEN
