### ISSUE TITLE
糟糕！ 不支持 armv7l 平台呀

### ISSUE THREAD

**Issue by weekdayjast** [learnhard-cn/clash#46]
**详述您希望的功能是什么样的？**
如果您建议的功能合理或者很多人都很需要，作者会听取您的建议，将这个功能实现并加入到本项目中。

**功能描述**

在这里描述您的功能需求或者建议内容。

**附加信息**

您希望额外表达的内容.

2024年06月13日11:31:15:clash: Clash版科学上网插件开始安装！
2024年06月13日11:31:15:clash: CPU架构: armv5 符合安装要求!
2024年06月13日11:31:15:clash: KoolShare目录存在，继续检测固件平台支持!
2024年06月13日11:31:15:clash: 糟糕！ 不支持 armv7l 平台呀！ 您的路由器型号: ,固件类型：  ,固件版本：380 ,请将安装过程日志内容(上面的所有内容)复制好后反馈给开发者,以便于帮您找到安装失败原因！反馈地址: https://github.com/vxiaov/vClash/issues/

**Comment by Awkee** [comment]
有针对380版本固件的版本，你是不是安装了支持386版本固件的版本导致的呢？
