### ISSUE TITLE
/tmp/clash/install.sh: source: line 10: can't open '/koolshare/scripts/base.sh'

### ISSUE THREAD

**Issue by bugcapablity** [learnhard-cn/clash#47]
**Bug描述**
固件为[3.0.0.4.386_JDCAX1800_B5.2.5]
route@JDCAX1800-6F5D:/tmp# sh /tmp/clash/install.sh
/tmp/clash/install.sh: source: line 10: can't open '/koolshare/scripts/base.sh'

**Bug重现**
描述触发Bug的步骤:
1. [image](https://github.com/vxiaov/vClash/assets/114269869/a6675d0b-e880-43fc-9046-471984573bf5)
2. ![image](https://github.com/vxiaov/vClash/assets/114269869/e8166571-d800-4fb3-b729-33daabc82424)
3. 开启ssh本地安装 
4. cd /tmp
tar -zxvf /tmp/clash.tar.gz
chmod +x /tmp/clash/install.sh
sh /tmp/clash/install.sh
![image](https://github.com/vxiaov/vClash/assets/114269869/a78d5a0b-071d-4f95-882c-74873396f6ff)

**路由器信息:**
您可以手工填写如下信息:
 - 路由器型号:JDCAX1800
 - 固件类型: Koolcenter_梅林改版
 - 固件版本: 386

**Comment by bugcapablity** [comment]
路由是京东colud ax1800 pro,大佬能帮忙看看吗, 感谢感谢

**Comment by bugcapablity** [comment]
破案了，386的clash，但不支持armv7l架构

**Comment by Awkee** [comment]
armv7l架构选择 release 目录下 clash.armv5.tar.gz 这个安装包。

这个拆分的原因是这样的：

> 软件中心自带的安装脚本会检测 /jffs 分区空间大小，如果包含了支持 armv7l 和 aarch64 架构的clash内核就会导致安装包太大而无法安装。


我需要更新一下README.md 说明文档，提示一下这个问题。
