### ISSUE TITLE
[FEATURE] 停更的380版本如何实现自定义yaml？

### ISSUE THREAD

**Issue by timesd** [learnhard-cn/clash#48]
您好，我了解到380版本已经不再维护，但我希望能继续在老平台上使用该版本。
我想请教在这个停止更新的版本上，如何实现自定义YAML或替换内核？尤其是，我希望能够使用TUN功能，但发现主流的Merlin Clash项目并不支持这一功能，因此特别关注到您的项目。
非常感谢您的帮助。

**Comment by Awkee** [comment]
更换内核相对简单： 本项目主页上列出了目前可用的两个Clash内核项目，找到适合自己路由器的架构类型，这里据个例子
在路由器上执行`uname -m` 命令，如果输出的是 `aarch64`那么选择 带有 `linux-arm64` 的可执行程序下载并替换 名为 clash 的程序文件。

能否使用TUN功能的检测： ssh登录路由器上后台后查看是否有 /dev/net/tun 或 /dev/tun 设备文件，有的话才能使用TUN功能，很多路由器固件是没有此功能的。即使有TUN功能支持，但路由器设备上使用Clash的TUN功能性能并不好，反而推荐使用TPROXY实现透明代理。

这些其实很难一句两句的解释清楚，想自己实现最好配以个ChatGPT助手帮你，很多概念它可以帮你解答。

**Comment by timesd** [comment]
非常感谢回答！我照着探索下！
