### ISSUE TITLE
上传yaml配置不显示，编辑yaml文件保存失败

### ISSUE THREAD

**Issue by eric-hu519** [learnhard-cn/clash#49]
**Bug描述**
在可选配置界面，选择文件上传配置后，虽然下方黄字提示上传成功，但是启动配置中依然无法找到我上传的配置文件。另外在在线编辑界面中也无法找到上传的配置，尝试重新进入插件后依然无法找到上传的配置。

后续我尝试了直接编辑已有配置文件，点击编辑按钮后，将自己配置文件中的内容复粘贴到在线编辑界面中，然后点击保存，下方黄字提示保存成功，但实际日志输出保存失败。

**Bug重现**
详见截图GIF

**截图**
上传配置问题复现
![20240701_133238](https://github.com/vxiaov/vClash/assets/78285086/9c4db6d1-b581-4cc0-af77-df4719587cb4)
编辑配置问题复现
![20240701_133642](https://github.com/vxiaov/vClash/assets/78285086/cf7a5d36-fde9-4746-83cc-49151e96cc31)

**路由器信息:**
+---------------------------------------------------------------+
| 操作系统 : Linux RT-AX86U_Pro-3558 4.19.183 aarch64 RT-AX86U_PRO_Koolcenter_mod|
| 固件版本 : RT-AX86U_PRO:koolshare梅林改版固件:388|
| 内存使用 : free: 509.66 MB,total: 994.71 MB,usage:  48.76%|
| 磁盘空间 : free: 478.68 MB,total: 1647.69 MB,usage:  64.82%|
+---------------------------------------------------------------+
|>> vClash当前正在使用的软件版本：                                  |
|              vClash : v2.15.16                                |
/koolshare/scripts/clash_control.sh: line 1308: clash: not found
|       clash_premium :                                         |
|                  yq : 4.13.2                                  |
|                  jq : jq-1.5rc2-245-g7b81a83-dirty            |
|>> vClash初始安装包自带的软件版本(分析是否个人更改过):                |
|              vClash : v2.15.16                                |
|       clash_premium : 2023.08.17                              |
|                  yq : 4.13.2                                  |
|                  jq : jq-1.5                                  |
+---------------------------------------------------------------+
vClash的转发规则,分析转发规则是否正常:
IPv4 地址配置 NAT 规则:
+---------------------------------------------------------------+
IPv4 地址配置 mangle 规则:
+---------------------------------------------------------------+
IPv6 地址配置 mangle 规则:
+---------------------------------------------------------------+

**Comment by Awkee** [comment]
问题已经了解，但我并没有在AX86U上实测过本插件，因此问题分析还要靠你自己，我的建议是：

1. 从信息中看/jffs磁盘空间是足够的， 但还是建议查看下 /koolshare/clash 目录所在分区的空间是否足够 。
2. 检查一下  /koolshare/clash/config 目录的权限是否为 rwx 可读写访问权限。

如果以上都没问题，建议重新安装一次，并将安装过程的日志发出来看一下，是否在安装过程中发生什么错误了。

**Comment by eric-hu519** [comment]
> 问题已经了解，但我并没有在AX86U上实测过本插件，因此问题分析还要靠你自己，我的建议是：
> 
> 
> 
> 1. 从信息中看/jffs磁盘空间是足够的， 但还是建议查看下 /koolshare/clash 目录所在分区的空间是否足够 。
> 
> 2. 检查一下  /koolshare/clash/config 目录的权限是否为 rwx 可读写访问权限。
> 
> 
> 
> 如果以上都没问题，建议重新安装一次，并将安装过程的日志发出来看一下，是否在安装过程中发生什么错误了。
> 
> 
> 
> 

首先安装应该是没问题的，第二个问题已解决，如果一次性复制字数过多就无法写入保存，分段复制可以解决该问题；第一个问题的话，分区应该是足够的，后面我推测是可能配置文件中存在不受支持的unicode符号导致上传后无法加载

**Comment by Awkee** [comment]
@eric-hu519 这个问题之前我在脚本里加了保存的文本大小判断，文件内容太大的确会这样，但现在我去掉了这个判断，所以就没有任何错误显示。
这个好像 dbus 保存value值(即文本内容)长度限制问题。
文本保存逻辑是这样的： 文本内容 base64加密保存在 dbus 的一个key中，然后 web api接口获取这个值，解码base64数据就看到文本内容了。

**Comment by eric-hu519** [comment]
> @eric-hu519 这个问题之前我在脚本里加了保存的文本大小判断，文件内容太大的确会这样，但现在我去掉了这个判断，所以就没有任何错误显示。
> 
> 这个好像 dbus 保存value值(即文本内容)长度限制问题。
> 
> 文本保存逻辑是这样的： 文本内容 base64加密保存在 dbus 的一个key中，然后 web api接口获取这个值，解码base64数据就看到文本内容了。
> 
> 

好的，感谢！

**Comment by wxjback** [comment]
同样的问题，没看明白上面最终是如何成功保存或上传？
