### ISSUE TITLE
配置文件如何替换？

### ISSUE THREAD

**Issue by ercifang** [learnhard-cn/clash#53]
大佬，主面板四个启动配置，想把桌面版的订阅配置导进去，导入后主面板还是那四个配置，该如何替换这四个配置文件？

**Comment by Awkee** [comment]
1.导入配置： "可选配置“-》”上传启动配置“
2.覆盖现有配置: 比如覆盖 ”config_norelay.yaml" 配置内容，在“在线编辑”页面选中“config_norelay.yaml"配置文件，然后点击编辑，将你的配置粘贴在这里，Ctrl+S保存内容，最后重启一下服务即可。
